apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-backend
  template:
    metadata:
      labels:
        app: stock-backend
    spec:
      containers:
        - name: stock-backend
          image: stock-backend:v8
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
